# fly.toml app configuration file generated for n8n-custom on 2025-07-19T11:31:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8n-custom'
primary_region = 'gru'

[build]

[env]
  N8N_PORT = "8080"
  WEBHOOK_TUNNEL_URL = "https://n8n-custom.fly.dev"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
